# Site settings
title: Otevřená města
keywords: otevřené fungování radnice, open-source software
url: http://www.otevrenamesta.cz
baseurl: "" # the subpath of your site, e.g. /blog/


# Build settings
sass:
    sass_dir: assets/_sass
    style: :compressed

permalink:     :title.html

# Build settings
markdown: kramdown
