# Site settings
title: Otevřená města
keywords: software, opensource, Piráti
baseurl: "" # the subpath of your site, e.g. /blog/
gems:
    - jekyll-sitemap

# Build settings
sass:
    sass_dir: assets/_sass
    style: :compressed
